version: "3.9"

services:

  web:
    build: .
    container_name: puntosred_web

    ports:
      - "8080:80"

    volumes:
      - C:/xampp/htdocs/puntos_red:/var/www/html

    depends_on:
      - mysql

  mysql:
    image: mysql:8.4

    container_name: puntosred_mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: puntos_red

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin

    container_name: puntosred_phpmyadmin

    restart: always

    ports:
      - "8081:80"

    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root

    depends_on:
      - mysql

volumes:

  mysql_data: