version: "3.9"

services:
mysql:
  image: mysql:8.4
  container_name: puntosred_mysql
  restart: always

  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: puntos_red

  ports:
    - "3306:3306"

  volumes:
    - mysql_data:/var/lib/mysql
    - ./sql:/docker-entrypoint-initdb.d